name: Cypress tests

on:
  pull_request:
     branches: [main]
     types: [labeled]
     
  issue_comment:
    types: [created]
    
  workflow_dispatch:


jobs:
  pr_labeled:
      name: PR Labeled
      runs-on: ubuntu-latest
      steps:
        - name: pr_labeled
          id: check_label 
          run: exit 0
          if: contains( github.event.pull_request.labels.*.name, 'test')
        - name: otherwise
          run: exit 1
          if: false == contains( github.event.pull_request.labels.*.name, 'test')
          
  cypress-test:
    name: Run on Chrome 83
    needs: pr_labeled
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
      - name: Pre-checkout
        uses: actions/checkout@v2
      
      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
          
      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: false
        
      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots
          
      - name: Merge test reports
        run: npm run combine:report
        
      - name: Generate HTML report
        run: npm run generate:report
       
      - name: Deploy report page to Github Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        
